/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ArrayConfiguration.java
 *
 * Created on 07.11.2009, 15:52:29
 */
package gui.dialogs.configuration;

/**
 *
 * @author sylvester
 */
class ArrayConfiguration extends ConfigurationPanel {

	/**
	 * Creates new form ArrayConfiguration
	 * 
	 * @deprecated Only for GUI Builder
	 */
	public ArrayConfiguration() {
		this(null);
	}

	public ArrayConfiguration(ConfigureDialog.ParameterNode listeningNode) {
		super(listeningNode);
		initComponents();
		this.nameLabel.setText(this.getParameterName());

		this.updateValue();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 29));

        addButton.setText("Add Item");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove Item");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        nameLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(removeButton)
                .addComponent(addButton)
                .addComponent(nameLabel))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
		this.setValue(++childCount);
	}//GEN-LAST:event_addButtonActionPerformed

	private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
		if (childCount > 0)
			this.setValue(--childCount);
	}//GEN-LAST:event_removeButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
	private int childCount = 0;

	protected void updateValue() {
		if (this.getValue() instanceof Integer)
			this.childCount = (Integer) this.getValue();
	}

}
