/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StringConfiguration.java
 *
 * Created on 07.11.2009, 15:23:33
 */
package gui.dialogs.configuration;

/**
 *
 * @author sylvester
 */
public class BooleanConfiguration extends ConfigurationPanel {

	/**
	 * Creates new form StringConfiguration
	 *
	 * @deprecated Only for GUI Designer
	 */
	public BooleanConfiguration() {
		this(null);
	}

	public BooleanConfiguration(ConfigureDialog.ParameterNode listeningNode) {
		super(listeningNode);
		initComponents();
		this.valueCheckbox.setText(this.getParameterName());
		this.updateValue();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueCheckbox = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(500, 27));

        valueCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(valueCheckbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(valueCheckbox)
        );
    }// </editor-fold>//GEN-END:initComponents

	private void valueCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueCheckboxActionPerformed
		this.setValue(this.valueCheckbox.isSelected());
	}//GEN-LAST:event_valueCheckboxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox valueCheckbox;
    // End of variables declaration//GEN-END:variables

	protected void updateValue() {
		if (this.getValue() instanceof Boolean)
			this.valueCheckbox.setSelected((Boolean) this.getValue());
	}
}
