
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *                                                                           *
 * Copyright 2009 Lars Hupel, Torben Maack, Sylvester Tremmel                *
 *                                                                           *
 * This file is part of Jamog.                                               *
 *                                                                           *
 * Jamog is free software: you can redistribute it and/or modify             *
 * it under the terms of the GNU General Public License as published by      *
 * the Free Software Foundation; version 3.                                  *
 *                                                                           *
 * Jamog is distributed in the hope that it will be useful,                  *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of            *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the              *
 * GNU General Public License for more details.                              *
 *                                                                           *
 * You should have received a copy of the GNU General Public License         *
 * along with Jamog. If not, see <http://www.gnu.org/licenses/>.             *
 *                                                                           *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
package gui;

import gui.dialogs.AboutWindow;
import gui.dialogs.SettingsDialog;
import java.awt.event.WindowEvent;
import core.build.Machine;
import gui.util.Utilities;
import java.awt.CardLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.WindowFocusListener;
import java.awt.image.BufferedImage;
import javax.swing.JDialog;

/**
 *
 * @author sylvester
 */
public class MainWindow extends javax.swing.JFrame {

	/** Creates new form MainWindow */
	public MainWindow() {
		initComponents();
		this.setLocationRelativeTo(null);

		this.addWindowFocusListener(new WindowFocusListener() {

			@Override
			public void windowGainedFocus(WindowEvent e) {
				if (MainWindow.this.machinePanel != null)
					ViewManager.getInstance().focusView(MainWindow.this.machinePanel.getCircuitPanelGroup().getCurrentView());
			}

			@Override
			public void windowLostFocus(WindowEvent e) {
				// Do nothing
			}

		});
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel() {
            private BufferedImage image;

            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D graphics = (Graphics2D) g;
                graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                if (this.image == null)
                this.image = Utilities.getImage("Background.png", false);
                graphics.drawImage(this.image, this.getWidth() - this.image.getWidth(), this.getHeight() - this.image.getHeight(), Utilities.imageObserver);
                graphics.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 30));
                graphics.drawString("Jamog", 100, 100);
                graphics.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 12));
                graphics.drawString("Just a mæss of gates.", 100, 125);
                graphics.setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 12));
                graphics.drawString("Use the \"Machine\" menu to create new machine or open an existing one.", 100, 160);
            }
        };
        menuBar = new javax.swing.JMenuBar();
        machineMenu = new javax.swing.JMenu();
        newMachineMenuItem = new javax.swing.JMenuItem();
        openMachineMenuItem = new javax.swing.JMenuItem();
        saveMachineMenuItem = new javax.swing.JMenuItem();
        closeMachineMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        settingsMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        exitMenuItem = new javax.swing.JMenuItem();
        settingsMenu = new javax.swing.JMenu();
        manageComponentPathsMenuItem = new javax.swing.JMenuItem();
        showSettingsMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboundMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jamog");
        setLocationByPlatform(true);

        mainPanel.setLayout(new java.awt.CardLayout());

        machineMenu.setText("Machine");

        newMachineMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMachineMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/famfamfam/cog_add.png"))); // NOI18N
        newMachineMenuItem.setText("Create new machine");
        newMachineMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMachineMenuItemActionPerformed(evt);
            }
        });
        machineMenu.add(newMachineMenuItem);

        openMachineMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMachineMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/famfamfam/folder.png"))); // NOI18N
        openMachineMenuItem.setText("Open machine");
        machineMenu.add(openMachineMenuItem);

        saveMachineMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMachineMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/famfamfam/disk.png"))); // NOI18N
        saveMachineMenuItem.setText("Save machine");
        machineMenu.add(saveMachineMenuItem);

        closeMachineMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        closeMachineMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/famfamfam/cog_delete.png"))); // NOI18N
        closeMachineMenuItem.setText("Close machine");
        machineMenu.add(closeMachineMenuItem);
        machineMenu.add(jSeparator2);

        settingsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/famfamfam/cog_edit.png"))); // NOI18N
        settingsMenuItem.setText("Machine settings");
        machineMenu.add(settingsMenuItem);
        machineMenu.add(jSeparator1);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/famfamfam/door_in.png"))); // NOI18N
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        machineMenu.add(exitMenuItem);

        menuBar.add(machineMenu);

        settingsMenu.setText("Settings");

        manageComponentPathsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/famfamfam/folder.png"))); // NOI18N
        manageComponentPathsMenuItem.setText("Manage component pathes");
        manageComponentPathsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageComponentPathsMenuItemActionPerformed(evt);
            }
        });
        settingsMenu.add(manageComponentPathsMenuItem);

        showSettingsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/famfamfam/cog_edit.png"))); // NOI18N
        showSettingsMenuItem.setText("Settings");
        showSettingsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSettingsMenuItemActionPerformed(evt);
            }
        });
        settingsMenu.add(showSettingsMenuItem);

        menuBar.add(settingsMenu);

        helpMenu.setText("Help");

        aboundMenuItem.setText("About Jamog");
        aboundMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboundMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboundMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newMachineMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMachineMenuItemActionPerformed
		Machine machine = new Machine("New Machine", "This is an automatically generated machine using a sequential simulator.");
		this.machinePanel = new MachinePanel(machine);
		this.mainPanel.add(this.machinePanel, "MachinePanel");
		this.mainPanel.validate();
		((CardLayout) this.mainPanel.getLayout()).show(this.mainPanel, "MachinePanel");
		this.setTitle("Jamog - " + machine.getName());
}//GEN-LAST:event_newMachineMenuItemActionPerformed

	private void aboundMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboundMenuItemActionPerformed
		this.aboutWindow.setVisible(true);
	}//GEN-LAST:event_aboundMenuItemActionPerformed

	private void manageComponentPathsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageComponentPathsMenuItemActionPerformed
		this.settingsDialog.setVisible(true);
	}//GEN-LAST:event_manageComponentPathsMenuItemActionPerformed

	private void showSettingsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSettingsMenuItemActionPerformed
		this.settingsDialog.setVisible(true);
	}//GEN-LAST:event_showSettingsMenuItemActionPerformed

	private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
		System.exit(0);
	}//GEN-LAST:event_exitMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboundMenuItem;
    private javax.swing.JMenuItem closeMachineMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenu machineMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem manageComponentPathsMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newMachineMenuItem;
    private javax.swing.JMenuItem openMachineMenuItem;
    private javax.swing.JMenuItem saveMachineMenuItem;
    private javax.swing.JMenu settingsMenu;
    private javax.swing.JMenuItem settingsMenuItem;
    private javax.swing.JMenuItem showSettingsMenuItem;
    // End of variables declaration//GEN-END:variables
	private AboutWindow aboutWindow = new AboutWindow();
	private JDialog settingsDialog = new SettingsDialog(this, true);
	private MachinePanel machinePanel;
}
